// <auto-generated />
namespace aulaWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alt6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alt6));
        
        string IMigrationMetadata.Id
        {
            get { return "201609102332067_Alt6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
